import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="text-rum-50 min-h-screen grid grid-rows-[auto_1fr]">
          <NavBar />
          <div className="bg-zinc-900 flex justify-center align-middle">
            {children}
          </div>
         
        </div> 
      </body>
    </html>
  );
}
